############### Defaults ###############
########################################
PARAMS: &defaults

  # PROCESSING PARAMETERS
  EXTRA_PAUSE   : 0     # extra pause in case some arrays are extra latent (Dillingham)
  FREQMIN       : 0.8   # minimum frequency
  FREQMAX       : 5.0   # maximum frequency
  TAPER         : 5.0   # seconds to taper beginning and end of trace before filtering
  WINDOW_LENGTH : 30    # window length for each calculation [seconds]
  OVERLAP       : 15    # amount of overlap between windows [seconds]
  MIN_CHAN      : 3     # minimum number of channels needed to perform inversion
  LTS_ALPHA     : 0.75  # decimal [0.50, 1.0] amount of data to keep in the subsets

  # PLOTTING PARAMETERS
  PLOT_MCCM     : True  # make MdCCM scatter subplot
  MCTHRESH      : 0.6   # where to draw the threshold line in MCCM plot
  AZ_MIN        : 0     # minimum azimuth to plot
  AZ_MAX        : 360   # maximum azimuth to plot
  VEL_MIN       : 0.25  # minimum sound speed range
  VEL_MAX       : 0.45  # maximum sound speed range
  ARRAY_LABEL   : Infrasound
########################################
########################################

STATION_XML: data/example_2/AVO_station.xml
TARGETS_FILE: data/example_2/AVO_volcano_list.txt

# Define arrays to be processed
NETWORKS:
  AVO:
    - Kenai
    - Sand Point

# Configure each array's channels, back-azimuth targets, 
# and (optionally) different pre-processing/plotting parameters
Kenai:
  <<: *defaults
  NSLC: 
    - AV.KENI.01.HDF
    - AV.KENI.02.HDF
    - AV.KENI.03.HDF
    - AV.KENI.04.HDF
    - AV.KENI.05.HDF
    - AV.KENI.06.HDF
  TARGETS: 
    - Wrangell
    - Spurr
    - Redoubt
    - Iliamna
    - Augustine
  AZ_MIN: 200
  AZ_MAX: 80

Sand Point:
  <<: *defaults
  NSLC: 
    - AV.SDPI.01.HDF
    - AV.SDPI.02.HDF
    - AV.SDPI.03.HDF
    - AV.SDPI.04.HDF
    - AV.SDPI.05.HDF
    - AV.SDPI.06.HDF
  TARGETS: 
    - Pavlof
    - Veniaminof
    - Shishaldin
    - Trident
  AZ_MIN: 240
  AZ_MAX: 60
  FREQMIN: 1

