########## Data Source ##########
CLIENT_TYPE: fdsn  # <obspy client type (earthworm, fdsn, local_fdsn, sds, seedlink)>
HOSTNAME: iris     # <fdsn name or server ip_address>
PORT:              # <int (if relevant)>
TIMEOUT: 10        # optional. Defaults to 30
LATENCY: 60        # how long to pause and wait for data latency to catch up before processing (seconds)
#################################

############ Output #############
OUT_WEB_DIR: ../output/html
OUT_ASCII_DIR: ../output/ascii_output
LOGS_DIR: ../output/logs
#################################

# Optional array config file location.
# This can be set here, or as an environment variable.
# If neither is set, it defaults to ../config/arrays_config.yml
# 
ARRAYS_CONFIG: 
  - ../config/example_2/AVO_arrays_config.yml
  - ../config/example_2/CNMI_arrays_config.yml


## Optional urls that get linked from the iPensive webpage
EXTRA_LINKS:
  - Data Output: ../tests/ascii_output/
  - AK Array Locations: https://ds.iris.edu/gmap/#network=AV&location=01&channel=HDF&planet=earth
  - CNMI Array Locations: https://ds.iris.edu/gmap/#network=MI,IM&station=FLX,H11N1,H11S1&planet=earth


# Example data source configurations:
############ Winston ############
# CLIENT_TYPE: earthworm
# HOSTNAME: ip_address
# PORT: number
# TIMEOUT: 10       # optional. Defaults to 30
#################################

############## CWB ##############
# CLIENT_TYPE: earthworm
# HOSTNAME: ip_address
# PORT: number
# TIMEOUT: 10       # optional. Defaults to 30
#################################

############# FDSN ##############
# CLIENT_TYPE: fdsn
# HOSTNAME: url (or obspy mapped name: e.g. IRIS)
# TIMEOUT: 10       # optional. Defaults to 30
#################################

########## LOCAL FDSN ###########
# CLIENT_TYPE: local_fdsn
# LOCAL_FDSN: local_url (e.g. http://localhost:8080/fdsnws/dataselect)
# TIMEOUT: 10       # optional. Defaults to 30
#################################

############## SDS ##############
# CLIENT_TYPE: sds
# DIRECTORY: <path_to_data_directory>
# FMT: {network}/{year}/{doy:03d}/{station}.{network}.{year}.{doy:03d}
#################################

############ seedlink ############
# CLIENT_TYPE: seedlink
# HOSTNAME: seedlink_hostname
# PORT: seedlink_port
# TIMEOUT: 10       # optional. Defaults to 30.
#################################