---
image: python:3.12

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip

stages:
  - test
  - build

test:
  stage: test
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11", "3.13"]
  image: python:$PYTHON_VERSION
  before_script:
    - pip install --upgrade pip
    - pip install -e .[test]
  script:
    - pytest -v

coverage:
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install -e .[test]
  script:
    - coverage run -m pytest
    - coverage report
  coverage: '/(?i)total.*? ([1-9]?\d|100)\%$/'

build:image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - >-
      docker build
      --no-cache
      --provenance=false
      --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}
      --tag $CI_REGISTRY_IMAGE:latest
      .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}
    - docker push $CI_REGISTRY_IMAGE:latest
