########## AVO Winston ##########
CLIENT_TYPE: earthworm
HOSTNAME: pubavo1.wr.usgs.gov
PORT: 16022
#################################

########### NEIC CWB ############
# CLIENT_TYPE: earthworm
# HOSTNAME: ip_address
# PORT: number
#################################

############# IRIS ##############
# CLIENT_TYPE: fdsn
# HOSTNAME: IRIS
#################################

########## LOCAL FDSN ###########
# CLIENT_TYPE: local_fdsn
# LOCAL_FDSN: http://localhost:8080/fdsnws/dataselect
#################################

############## SDS ##############
# CLIENT_TYPE: sds
# DIRECTORY: <path_to_data_directory>
# FMT: "{network}/{year}/{doy:03d}/{station}.{network}.{year}.{doy:03d}"
#################################

############ seedlink ############
# CLIENT_TYPE: seedlink
# HOSTNAME: seedlink_hostname
# PORT: seedlink_port
#################################